main: me.hozukizdev.CraftoriaRealmsVOAR.main.CraftoriaRealmsVOAR
name: CraftoriaRealmsVOAR
version: 1.0
author: HozukizDEV

commands:
  voar:
    description: Ativa ou Desativa o voo
    usage: /voar

permissions:
  craftoriavoar.use:
    description: Permite usar o comando /voar
    default: op
  craftoriavoar.reload:
    description: Permite usar o subcomando /voar reload
    default: op